### ISSUE TITLE
Could not get unknown property 'konanDevPath' for project ':buildSrc:shared' of type org.gradle.api.Project

### ISSUE THREAD

**Issue by luca992** [touchlab/knarch.db#50]
When building I realize konanDevPath should point to a kotlin native project folder... But where are you defining konanDevPath?

**Comment by kpgalligan** [comment]
That's defined in

```
~/.gradle/gradle.properties
```

It points to a clone of the kotlin native repo. You'll need to try to use the same version you're building for, obviously.

This project is kind of a weird setup compared to what will probably appear in most libraries. The C++ portion needs access to the headers defined for the native runtime.

It would probably make sense to refactor the build and include the headers in the repo, but other things are higher on the current list.
