### ISSUE TITLE
Android build issue

### ISSUE THREAD

**Issue by IgorGanapolsky** [touchlab/knarch.db#53]
Hello,
upon building the android codebase, I get this error:
> ERROR: Failed to resolve: co.touchlab.knarch.threads:threads-common:0.2.3

Any ideas?

**Comment by kpgalligan** [comment]
The samples were super old. I updated the raw sample and removed the sqldelight sample (see [Droidcon](https://github.com/touchlab/DroidconKotlin/) for a live Sqldelight sample)
